// Generated by CoffeeScript 1.9.2
(function() {
  var Intro1Layer,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Intro1Layer = (function(superClass) {
    extend(Intro1Layer, superClass);

    Intro1Layer.prototype.initLayerWe = function() {
      this.layerWe = new Layer({
        image: '/imported/PAI-updated/images/Intro-1-We.png',
        x: 82.92,
        y: 197.4,
        width: 107,
        height: 47,
        opacity: 0
      });
      this.layerWe.originalOriginX = this.layerWe.originX;
      this.layerWe.originalOriginY = this.layerWe.originY;
      this.layerWe.originX = 0;
      this.layerWe.originY = 0;
      this.layerWe.scaleX = this.width / 3322;
      this.layerWe.scaleY = this.height / 2000;
      this.layerWe.superLayer = this;
      this.layerWeAnimationFadeIn = new Animation({
        time: 3,
        layer: this.layerWe,
        properties: {
          opacity: 1
        }
      });
      this.layerWeAnimationRotate = new Animation({
        time: 10,
        layer: this.layerWe,
        properties: {
          rotation: this.layerWe.rotation + 360
        },
        curve: "spring(800,25,0)"
      });
      this.layerWeAnimationFadeIn.on(Events.AnimationStart, this.onLayerWeAnimationFadeInStarted);
      this.layerWeAnimationFadeIn.on(Events.AnimationEnd, this.onLayerWeAnimationFadeInEnded);
      return this.layerWeAnimationRotate.on(Events.AnimationEnd, this.onLayerWeAnimationRotateEnded);
    };

    function Intro1Layer(options) {
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      this.onLayerWeAnimationFadeInEnded = bind(this.onLayerWeAnimationFadeInEnded, this);
      this.onLayerWeAnimationFadeInStarted = bind(this.onLayerWeAnimationFadeInStarted, this);
      this.onLayerWeAnimationRotateEnded = bind(this.onLayerWeAnimationRotateEnded, this);
      this.initLayerCreate = bind(this.initLayerCreate, this);
      this.initLayerWe = bind(this.initLayerWe, this);
      Intro1Layer.__super__.constructor.call(this, {
        image: '/imported/PAI-updated/images/Intro-1.png',
        width: options.width,
        height: options.height,
        opacity: options.opacity
      });
      this.superLayer = options.superLayer;
    }

    Intro1Layer.prototype.initLayerCreate = function() {
      this.layerCreate = new Layer({
        image: '/imported/PAI-updated/images/Intro-1-Create.png',
        x: this.layerWe.x + this.layerWe.width * this.layerWe.scaleX,
        y: this.layerWe.y,
        width: 707,
        height: 145
      });
      this.layerCreate.originX = 0;
      this.layerCreate.originY = 0;
      this.layerCreate.superLayer = this;
      this.layerCreate.scaleX = this.layerWe.scaleX;
      this.layerCreate.scaleY = this.layerWe.scaleY;
      this.layerCreate.x = this.layerWe.x + this.layerWe.width * this.layerWe.scaleX + (80 * this.layerCreate.scaleX);
      this.layerCreate.y = this.layerWe.y + ((this.layerWe.height * this.layerWe.scaleY) / 2) - (this.layerCreate.height * this.layerCreate.scaleY) / 2;
      this.layerCreate.originalWidth = this.layerCreate.width;
      this.layerCreate.originalHeight = this.layerCreate.height;
      this.layerCreate.width = 0;
      this.layerCreate.originX = 1;
      return this.layerCreateSizeAnimation = new Animation({
        time: 2,
        layer: this.layerCreate,
        properties: {
          originX: 0,
          width: this.layerCreate.originalWidth
        }
      });
    };

    Intro1Layer.prototype.onLayerWeAnimationRotateEnded = function() {};

    Intro1Layer.prototype.onLayerWeAnimationFadeInStarted = function() {
      return console.log("onLayerWeAnimationStarted called");
    };

    Intro1Layer.prototype.onLayerWeAnimationFadeInEnded = function() {
      console.log("onLayerWeAnimationEnded called");
      return this.layerCreateSizeAnimation.start();
    };

    Intro1Layer.prototype.init = function() {
      this.initLayerWe();
      this.initLayerCreate();
      this.layerSpace = new Layer({
        image: '/imported/PAI-updated/images/Intro-1-Space.png',
        x: this.layerCreate.x,
        y: Screen.height + (Screen.height / 3),
        width: 250,
        height: 49,
        opacity: 1
      });
      this.layerSpace.superLayer = this;
      this.layerSpace.scaleX = this.layerCreate.scaleX;
      this.layerSpace.scaleY = this.layerCreate.scaleY;
      this.layerSpace.x = this.layerCreate.x + (780 * this.layerSpace.scaleX);
      this.layerSpace.states.add({
        stateOnTopMost: {
          y: 0
        },
        stateMiddle: {
          y: this.layerCreate.y
        },
        stateLeft: {
          x: this.layerSpace.x - (350 * this.layerSpace.scaleX)
        },
        stateRight: {
          x: this.layerSpace.x + (350 * this.layerSpace.scaleX)
        },
        stateFinal: {
          y: this.layerCreate.y,
          x: this.layerCreate.x + (780 * this.layerSpace.scaleX)
        }
      });
      this.layerSpace.animationEndCounter = 0;
      return this.layerSpace.on(Events.StateDidSwitch, (function(_this) {
        return function(a, stateName) {
          if (stateName !== 'stateFinal') {
            return _this.layerSpace.states.next();
          }
        };
      })(this));
    };

    Intro1Layer.prototype.play = function() {
      console.log("Intro1Layer.play called");
      this.layerWeAnimationFadeIn.start();
      return setTimeout((function(_this) {
        return function() {
          return _this.layerSpace.states.next();
        };
      })(this), 4000);
    };

    return Intro1Layer;

  })(Layer);

  module.exports = Intro1Layer;

}).call(this);
