// Generated by CoffeeScript 1.9.2
(function() {
  var ScreenBase, ScreenMainMenu,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ScreenBase = require("./ScreenBase");

  ScreenMainMenu = (function(superClass) {
    extend(ScreenMainMenu, superClass);

    function ScreenMainMenu() {
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      ScreenMainMenu.__super__.constructor.apply(this, arguments);
      this.layer = new Layer({
        backgroundColor: 'black',
        width: this.width,
        height: this.height
      });
      this.layerProfile = new Layer({
        backgroundColor: 'red',
        x: 0,
        y: 0,
        width: this.width / 2,
        height: this.height / 2
      });
      this.layerProfile.superLayer = this.layer;
      this.layerProjects = new Layer({
        backgroundColor: 'green',
        x: this.layerProfile.width,
        y: 0,
        width: this.width - this.layerProfile.width,
        height: this.height - this.layerProfile.height
      });
      this.layerProjects.superLayer = this.layer;
      this.layerPersonnel = new Layer({
        backgroundColor: 'blue',
        x: 0,
        y: this.layerProfile.height,
        width: this.layerProfile.width,
        height: this.layerProfile.height
      });
      this.layerPersonnel.superLayer = this.layer;
      this.layerContact = new Layer({
        backgroundColor: 'yellow',
        x: this.layerProjects.width,
        y: this.layerProjects.height,
        width: this.layerProjects.width,
        height: this.layerProjects.height
      });
      this.layerContact.superLayer = this.layer;
    }

    ScreenMainMenu.prototype.init = function() {
      return this.layer.center();
    };

    ScreenMainMenu.prototype.play = function() {};

    return ScreenMainMenu;

  })(ScreenBase);

  module.exports = ScreenMainMenu;

}).call(this);
