// Generated by CoffeeScript 1.9.2
(function() {
  var ScreenBase, ScreenMainMenu,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  ScreenBase = require("./ScreenBase");

  ScreenMainMenu = (function(superClass) {
    extend(ScreenMainMenu, superClass);

    function ScreenMainMenu() {
      this.play = bind(this.play, this);
      this.init = bind(this.init, this);
      ScreenMainMenu.__super__.constructor.apply(this, arguments);
      this.layer = new Layer({
        backgroundColor: 'red',
        width: this.width,
        height: this.height
      });
    }

    ScreenMainMenu.prototype.init = function() {
      return this.layer.center();
    };

    ScreenMainMenu.prototype.play = function() {};

    return ScreenMainMenu;

  })(ScreenBase);

  module.exports = ScreenMainMenu;

}).call(this);
