// Generated by CoffeeScript 1.9.2
(function() {
  var ScreenBase;

  ScreenBase = (function() {
    function ScreenBase() {
      this.width = 1024;
      this.height = 600;
    }

    return ScreenBase;

  })();

  module.exports = ScreenBase;

}).call(this);
