// Generated by CoffeeScript 1.9.2
(function() {
  var currentLayerIndex, fades, i, image, images, introLayers, isStart, layerIntro, len;

  images = ['/imported/PAI-updated/images/Intro 1.png', '/imported/PAI-updated/images/Intro 2.png', '/imported/PAI-updated/images/Intro 3.png', '/imported/PAI-updated/images/Intro 4.png'];

  introLayers = [];

  for (i = 0, len = images.length; i < len; i++) {
    image = images[i];
    layerIntro = new Layer({
      x: 0,
      y: 0,
      width: 1024,
      height: 600,
      image: image,
      opacity: 0
    });
    layerIntro.states.add({
      fadein: {
        opacity: 1
      },
      fadeout: {
        opacity: 0
      }
    });
    layerIntro.center();
    introLayers.push(layerIntro);
  }

  currentLayerIndex = 0;

  isStart = true;

  fades = (function(_this) {
    return function() {
      console.log(currentLayerIndex);
      if (currentLayerIndex > 0) {
        introLayers[currentLayerIndex - 1].states["switch"]("fadeout");
      } else {
        if (isStart) {
          isStart = false;
        } else {
          introLayers[introLayers.length - 1].states["switch"]("fadeout");
        }
      }
      introLayers[currentLayerIndex].states["switch"]("fadein");
      currentLayerIndex += 1;
      if (currentLayerIndex >= introLayers.length) {
        currentLayerIndex = 0;
      }
      return setTimeout(function() {
        return fades();
      }, 5000);
    };
  })(this);

  fades();

}).call(this);
