// Generated by CoffeeScript 1.9.2
(function() {
  var ScreenIntro, ScreenMainMenu, intro, mainMenu;

  ScreenIntro = require("./screens/ScreenIntro");

  ScreenMainMenu = require("./screens/ScreenMainMenu");

  mainMenu = null;

  intro = new ScreenIntro();

  intro.init();

  intro.onExit = (function(_this) {
    return function() {
      mainMenu = new ScreenMainMenu();
      mainMenu.init();
      return mainMenu.play();
    };
  })(this);

  intro.play();

}).call(this);
